### PR TITLE
Fix persistent vars map

### PR DESCRIPTION
**Pull request by necolas**
The module was not clearing out the variables map between function calls.

Would appreciate a sanity check, in case I've missed the reason why it was originally done like this.

cc @ianstormtaylor @anthonyshort

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
fix seems fine to me, i've only ever used it once at a time

**Comment by necolas** [comment]
Thanks. Me too. But I just dropped it into our development asset toolchain and the persistence manifested as an issue.

**Comment by tj** [comment]
my bad. this will still have the issue if the jsmap _is_ defined, we should clone it I guess

**Comment by necolas** [comment]
yeah good point

**Pull request merged**
