### PR TITLE
fixed for comments nested inside selectors

### PR DESCRIPTION
**Pull request by ianstormtaylor**
basically if you have a situation like this:

``` css
.logo {
  position: relative;
  display: inline-block;
  vertical-align: middle; /* not baseline, so we align up _and_ down */
  height: 1em; /* keep height constant regardless of innards */
  margin: 0; /* reset */
}
```

the comments will show up in the declarations, dunno if you want to fix this here or in `rework-visit` instead.

also seems like there's a newer version on npm then on github? so you might need to push and i might need to rebase before this gets merged in

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
just realized this never got merged in. any objections?

**Comment by tj** [comment]
just hadn't seen it yet, cant believe this lib is a month old already wtf, not enough time haha

**Comment by tj** [comment]
shit yeah wont merge. the comment stuff is a bit tricky, having them mixed in the declarations is the easiest for compilation ATM, but ideally we move them out completely

**Comment by ianstormtaylor** [comment]
fixed.

makes sense that a better longterm solution would be to move them out completely.

**Comment by tj** [comment]
yea just tricky to stitch them back into the correct spot after you've already manipulated everything (and potentially removed associated nodes etc). The easiest would be to reference the node before and just inject them back in after those but then our css-parse output isn't json-friendly which is a little lame

**Pull request merged**
