### PR TITLE
PR: Limit var definitions to root

### LINKED ISSUE #15: Limit var definitions to `:root`
- [x] Enforce global variables by ignoring anything not declared in `:root`.
- [x] Collect all `:root` var definitions before replacement, to mimic all-at-once resolution of variable precedence.

### PR DESCRIPTION
**Pull request by necolas**
Up for peer-review

Fix gh-15

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
+1

**Comment by necolas** [comment]
This actually blows up if there's a media query in the CSS.

**Comment by necolas** [comment]
Should be ok now. Will throw an error if vars are set in media queries, until we can decide what to do in #17

**Comment by necolas** [comment]
Fixed by 1ec1555f54ca0c0ee3c9de1aea7b0044bdaca73a

**Pull request closed without merging**
